package Korus.Eds.Core;

public enum DocumentFormType {
  Other(0L),
  Invoice(1L),
  CorrectionInvoice(2L),
  Bill(3L),
  Torg12(4L),
  AcceptanceCertificate(5L),
  Act(6L),
  ReconciliationReport(7L),
  Agreement(8L),
  Document(9L),
  PriceList(10L),
  PriceListReconciliation(11L),
  ActAdd(12L),
  PlainBill(13L),
  NoticeDiscounts(14L),
  Infsoob(15L),
  DirectDebitContract(16L),
  Delivery(17L),
  RegistryUdt(18L),
  RegistryPdt(19L),
  Desadv(20L),
  Recadv(21L),
  CreditRequest(22L),
  CreditApplication(23L),
  CreditRequestReply(24L),
  CreditDocumentation(25L),
  CreditDocumentationConf(26L),
  UpdInvoice(27L),
  FeesRegisterInvestment(28L),
  UpdInvoiceInfo(29L),
  UpdInfo(30L),
  UpdCorrectionInvoice(31L),
  UpdCorrectionInvoiceInfo(32L),
  UpdCorrectionInfo(33L),
  ServiceRequest(34L),
  AdditionalFinancingRequest(35L),
  CancelFinancingRequest(36L),
  GoodsDeliveryReport(37L),
  WorksDeliveryReport(38L),
  ServiceKP(39L),
  ServiceTask(40L),
  ServiceContract(41L),
  ServiceDocRequest(42L),
  PaymentOrder(43L),
  ServiceDocResponse(44L),
  ServiceReportProject(45L),
  ServiceReport(46L),
  AgreementFpg(47L),
  FinancialMonitoringRequest(48L),
  FinancialMonitoringRequestReply(49L),
  BillUvhd(50L),
  ActProd(51L),
  SberbankNote(52L),
  CreditPaymentOrder(53L),
  TargetUse(54L),
  BankNotification(55L),
  BankRequirements(56L),
  ApplicationBusinessCard(57L),
  ApplicationPackageServices(58L),
  OrderGuarantee(59L),
  IkQualifyingSelection(60L),
  IkMonitoring(61L),
  IkReports(62L),
  BankingAccompaniment(63L),
  DocumentsForReestr(64L),
  ActAwardTander(65L),
  BankingServicesDocuments(66L),
  AcceptRealEstateFinansing(67L),
  ;
  private long numVal;

  DocumentFormType(long numVal) {
    this.numVal = numVal;
  }

  public long getNumVal() {
    return numVal;
  }
}
